[package]
name = "lang"
version = "0.1.0"
authors = ["graeme <graemephi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
bench = []
